name: kpconv
channels:
  - pytorch
  - defaults
dependencies:
  - numpy
  - scikit-learn
  - pyyaml

  # Develop and visualization
  - jupyter
  - matplotlib
  - mayavi
  - pyqt

  # PyTorch
  - pytorch
  - torchvision
  - torchaudio
  - cudatoolkit=11.0
